import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  // Unique app identifier in the stores. It cannot change after you publish.
  // Convention: reversed domain. Adjust it to your own domain if you have one.
  appId: 'com.kaplacc.mediatrack',
  appName: 'MediaTrack',
  webDir: 'out', // folder generated by `next build` with output: 'export'
  server: {
    androidScheme: 'https',
    iosScheme: 'https',
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 800,
      backgroundColor: '#0a0a0a',
      androidSplashResourceName: 'splash',
      showSpinner: false,
    },
    StatusBar: {
      style: 'DARK',
      backgroundColor: '#0a0a0a',
    },
    LocalNotifications: {
      smallIcon: 'ic_stat_icon',
      iconColor: '#3b82f6',
    },
  },
};

export default config;
